name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "jimber/threefold-connect-news:{{ github.sha }}"
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ secrets.ACTOR }} --password-stdin
      - name: Push to dockerhub
        run: docker push jimber/threefold-connect-news:{{ github.sha }}
